# Generated by Django 3.2.8 on 2023-05-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0016_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientsModel',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
